name: Build and Tag Charts

on:
  push:
    tags:
      - "chart-v*"

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          additional-helm-plugins: https://github.com/hayorov/helm-gcs.git

      - name: Docker Login
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Charts
        run: |
          pushd charts
          pushd community-operator
          helm dependency update
          helm package .
          helm push community-operator-*.tgz oci://ghcr.io/connamara-tech
          popd
